import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class UsersService {
  data: any = [
    {
      profilePicture: 'https://example.com/profile.jpg',
      personName: 'Aftab Ahmed',
      userName: 'aftab@csidryeye.com',
      userStatus: 'active',
      lastLogin: 'May 4, 2023 3:15 PM',
      userRole: 'Admin',
      userDepartment: 'Development',
      userTitle: 'CTO',
      assignmentSummary: 'All customers and clinics',
      assignmentInfo: [
        {
          clinicName: 'xyz clinic',
          assignedOn: 'May 4, 2023',
          assignedBy: 'Aftab Ahmed',
        },
        {
          clinicName: 'abc clinic',
          assignedOn: 'May 4, 2023',
          assignedBy: 'Aftab Ahmed',
        },
      ],
      userEmail: 'aftab@csidryeye.com',
      userPhone: '+1-202-555-0194',
      dateCreated: 'May 4, 2023',
    },
    {
      profilePicture: 'https://example.com/profile.jpg',
      personName: 'Trudy Sales',
      userName: 'trudy@csidryeye.com',
      userStatus: 'active',
      lastLogin: 'May 4, 2023 3:15 PM',
      userRole: 'Manager',
      userDepartment: 'Sales',
      userTitle: 'Chief Sales Officer',
      assignmentSummary: '10 clinics / 7 customers',
      assignmentInfo: [
        {
          clinicName: 'xyz clinic',
          assignedOn: 'May 4, 2023',
          assignedBy: 'Aftab Ahmed',
        },
        {
          clinicName: 'abc clinic',
          assignedOn: 'May 4, 2023',
          assignedBy: 'Aftab Ahmed',
        },
      ],
      userEmail: 'trudy@csidryeye.com',
      userPhone: '+1-202-555-0195',
      dateCreated: 'May 4, 2023',
    },
    {
      profilePicture: 'https://example.com/profile.jpg',
      personName: 'Yoab Kristy',
      userName: 'yoab@csidryeye.com',
      userStatus: 'inactive',
      lastLogin: 'May 4, 2021 3:15 PM',
      userRole: 'Member',
      userDepartment: 'Support',
      userTitle: 'Customer Support Specialist',
      assignmentSummary: '10 clinics / 7 customers',
      assignmentInfo: [
        {
          clinicName: 'xyz clinic',
          assignedOn: 'May 4, 2021',
          assignedBy: 'Aftab Ahmed',
        },
      ],
      userEmail: 'yoab@csidryeye.com',
      userPhone: '+1-202-555-0196',
      dateCreated: 'May 4, 2021',
    },
    {
      profilePicture: '',
      personName: 'Michael Smith',
      userName: 'MichaelSmith@csidryeye.com',
      userStatus: 'active',
      lastLogin: 'May 4, 2023 3:15 PM',
      userRole: 'Admin',
      userDepartment: 'Management',
      userTitle: 'Chief Executive Officer',
      assignmentSummary: '10 clinics / 7 customers',
      assignmentInfo: [
        {
          clinicName: 'xyz clinic',
          assignedOn: 'May 4, 2023',
          assignedBy: 'Aftab Ahmed',
        },
      ],
      userEmail: 'MichaelSmith@csidryeye.com',
      userPhone: '+1-202-555-0198',
      dateCreated: 'May 4, 2023',
    },
    {
      profilePicture: 'https://example.com/profile.jpg',
      personName: 'Alan Lamb',
      userName: 'alan@csidryeye.com',
      userStatus: 'deleted',
      lastLogin: 'May 4, 2021 3:15 PM',
      userRole: 'Manager',
      userDepartment: 'Management',
      userTitle: 'Chief Financial Officer',
      assignmentSummary: '10 clinics / 7 customers',
      assignmentInfo: [
        {
          clinicName: 'xyz clinic',
          assignedOn: 'May 4, 2021',
          assignedBy: 'Aftab Ahmed',
        },
      ],
      userEmail: 'alan@csidryeye.com',
      userPhone: '+1-202-555-0197',
      dateCreated: 'May 4, 2021',
    },
    {
      profilePicture: 'https://example.com/profile.jpg',
      personName: 'Dr. Al-Ghoul',
      userName: 'drghoul@csidryeye.com',
      userStatus: 'active',
      lastLogin: 'May 4, 2023 3:15 PM',
      userRole: 'Admin',
      userDepartment: 'Management',
      userTitle: 'Chief Medical Officer',
      assignmentSummary: '10 clinics / 7 customers',
      assignmentInfo: [
        {
          clinicName: 'xyz clinic',
          assignedOn: 'May 4, 2023',
          assignedBy: 'Aftab Ahmed',
        },
      ],
      userEmail: 'drghoul@csidryeye.com',
      userPhone: '+1-202-555-0198',
      dateCreated: 'May 4, 2023',
    },
    {
      profilePicture: '',
      personName: 'Emily Carter',
      userName: 'emily.carter@csidryeye.com',
      userStatus: 'active',
      lastLogin: 'May 4, 2023 3:15 PM',
      userRole: 'Admin',
      userDepartment: 'Management',
      userTitle: 'Chief Executive Officer',
      assignmentSummary: '10 clinics / 7 customers',
      assignmentInfo: [
        {
          clinicName: 'xyz clinic',
          assignedOn: 'May 4, 2023',
          assignedBy: 'Aftab Ahmed',
        },
      ],
      userEmail: 'emily.carter@csidryeye.com',
      userPhone: '+1-202-555-0198',
      dateCreated: 'May 4, 2023',
    },
    {
      profilePicture: '',
      personName: 'Rauf Chavez',
      userName: 'rauf.chavez@csidryeye.com',
      userStatus: 'pending',
      lastLogin: '',
      userRole: 'Member',
      userDepartment: 'Support',
      userTitle: 'Customer Support Specialist',
      assignmentSummary: '1 clinics / 1 customers',
      assignmentInfo: [
        {
          clinicName: 'xyz clinic',
          assignedOn: 'May 4, 2023',
          assignedBy: 'Aftab Ahmed',
        },
      ],
      userEmail: 'rauf.chavez@csidryeye.com',
      userPhone: '+1-202-555-0198',
      dateCreated: 'May 4, 2023',
    },
  ].sort((a, b) => a.personName.localeCompare(b.personName));

  constructor() {}
}
